PROJECT_NAME = trickle_node

TARGET ?= nrf52840ble-os
LIBDIR ?= $(CURDIR)/../../../..

SOURCE_FILES = \
	../distribution_service_worker.c \
	../distribution_service.c \
	../trickle_timer.c \
	node_app.c \

include $(LIBDIR)/Makefile.include
