PROJECT_NAME = trickle_root

TARGET ?= nrf52840ble-os
LIBDIR ?= $(CURDIR)/../../../..

SOURCE_FILES = \
	../distribution_service_worker.c \
	../distribution_service.c \
	../trickle_timer.c \
	root_app.c \

include $(LIBDIR)/Makefile.include
